enum CreationCoreAction {
    SET_ENTITY_CREATION_PARAMS="SET_ENTITY_CREATION_PARAMS",
    UPDATE_ENTITY_CREATION_PARAMS="UPDATE_CREATION_PARAMS",
    CREATE_ENTITY="CREATE_ENTITY",
    SET_ENTITY_VALIDATION_ERRORS="SET_ENTITY_VALIDATION_ERRORS",
    UPDATE_ENTITY_VALIDATION_ERRORS="UPDATE_ENTITY_VALIDATION_ERRORS"
}

export enum PersonCreationAction {
    UPDATE_PASSPORT_DATA="UPDATE_PASSPORT_DATA",
    ADD_PERSON_RELATION="ADD_PERSON_RELATION",
    REMOVE_PERSON_RELATION="REMOVE_PERSON_RELATION",
    UPDATE_PERSON_RELATION="UPDATE_PERSON_RELATION"
}

export default CreationCoreAction;




