export enum ExplorationCoreAction{
    SET_EXPLORATION_STATE="SET_EXPLORATION_STATE",
    SET_EXPLORATION_PARAMS="SET_EXPLORATION_PARAMS",
    UPDATE_EXPLORATION_PARAMS="UPDATE_EXPLORATION_PARAMS",
    RETRIEVE_DATA="RETRIEVE_DATA",
    SET_EXPLORATION_DATA="SET_EXPLORATION_DATA",
    SET_EXPLORATION_PARAMS_MODE="SET_EXPLORATION_PARAMS_MODE",
    SET_EXPLORATION_STATE_PENDING="SET_EXPLORATION_STATE_PENDING",
    SET_EXPLORATION_DATA_RESULTS="SET_EXPLORATION_DATA_RESULTS"
}


